# Generated by Django 5.2.6 on 2026-01-05 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("thesis", "Thesis"),
                            ("dissertation", "Dissertation"),
                            ("journal", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("project", "Project Report"),
                            ("book", "Book Chapter"),
                            ("dataset", "Dataset"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=200)),
                ("faculty", models.CharField(blank=True, max_length=200)),
                ("supervisor", models.CharField(blank=True, max_length=200)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("journal_name", models.CharField(blank=True, max_length=200)),
                ("volume", models.CharField(blank=True, max_length=50)),
                ("issue", models.CharField(blank=True, max_length=50)),
                ("pages", models.CharField(blank=True, max_length=50)),
                ("file", models.FileField(upload_to="repository/documents/")),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="repository/thumbnails/"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("open", "Open Access"),
                            ("restricted", "Restricted"),
                            ("embargoed", "Embargoed"),
                            ("private", "Private"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("embargo_date", models.DateField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("language", models.CharField(default="English", max_length=50)),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("issn", models.CharField(blank=True, max_length=20)),
                ("license", models.CharField(blank=True, max_length=200)),
                ("copyright_holder", models.CharField(blank=True, max_length=200)),
                ("rights_statement", models.TextField(blank=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("download_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="authored_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="repository.collection",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-submission_date", "title"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "is_active"],
                        name="repository__documen_138d36_idx",
                    ),
                    models.Index(
                        fields=["department", "year"],
                        name="repository__departm_8140dc_idx",
                    ),
                    models.Index(
                        fields=["-submission_date"],
                        name="repository__submiss_791d52_idx",
                    ),
                ],
            },
        ),
    ]
