# Generated by Django 5.2.6 on 2026-01-05 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=500, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("exhibition", "Exhibition"),
                            ("training", "Training"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/images/"
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=200)),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("is_online", models.BooleanField(default=False)),
                ("online_link", models.URLField(blank=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("requires_registration", models.BooleanField(default=False)),
                (
                    "registration_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("organizer_name", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("tags", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["start_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_attended", models.BooleanField(default=False)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                ("attendance_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registration_date"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_published", "start_date"],
                name="events_even_is_publ_08e85a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "is_published"],
                name="events_even_event_t_4cd3d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "is_confirmed"], name="events_even_event_i_ca76e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["user", "is_confirmed"], name="events_even_user_id_ae3153_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "user")},
        ),
    ]
