# Generated by Django 5.2.7 on 2025-12-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_event_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarydivision",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
