# Generated by Django 5.2.6 on 2026-01-05 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("circulation", "Circulation"),
                            ("catalog", "Catalog"),
                            ("repository", "Repository"),
                            ("users", "Users"),
                            ("events", "Events"),
                            ("blog", "Blog"),
                            ("system", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
                "ordering": ["-date", "metric_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "date"],
                        name="analytics_m_metric__044bd5_idx",
                    ),
                    models.Index(fields=["-date"], name="analytics_m_date_ce58f6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("circulation", "Circulation Report"),
                            ("catalog", "Catalog Report"),
                            ("repository", "Repository Report"),
                            ("users", "User Report"),
                            ("fines", "Fines Report"),
                            ("analytics", "Analytics Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/")),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("date_range_start", models.DateField(blank=True, null=True)),
                ("date_range_end", models.DateField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-generated_date"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "-generated_date"],
                        name="analytics_r_report__4bd59b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("result_count", models.IntegerField(default=0)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("catalog", "Catalog"),
                            ("repository", "Repository"),
                            ("blog", "Blog"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["search_type", "-created_at"],
                        name="analytics_s_search__a3fcf9_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="analytics_s_created_5d0a6f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("search", "Search"),
                            ("view_book", "View Book"),
                            ("view_document", "View Document"),
                            ("borrow", "Borrow Book"),
                            ("return", "Return Book"),
                            ("reserve", "Reserve Book"),
                            ("download", "Download Document"),
                            ("comment", "Comment"),
                            ("register_event", "Register Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analytics_u_user_id_39836b_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="analytics_u_action__93a4be_idx",
                    ),
                ],
            },
        ),
    ]
