# Generated by Django 5.2.6 on 2026-01-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_death", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Publisher",
                "verbose_name_plural": "Publishers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "isbn13",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("edition", models.CharField(blank=True, max_length=50)),
                ("language", models.CharField(default="English", max_length=50)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="book_qr_codes/"
                    ),
                ),
                ("total_copies", models.IntegerField(default=0)),
                ("available_copies", models.IntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("call_number", models.CharField(blank=True, max_length=100)),
                ("subject_heading", models.CharField(blank=True, max_length=500)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="catalog.author"),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.genre",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.publisher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["-created_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="Copy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_loan", "On Loan"),
                            ("reserved", "Reserved"),
                            ("maintenance", "Under Maintenance"),
                            ("lost", "Lost"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Copy",
                "verbose_name_plural": "Copies",
                "ordering": ["book", "barcode"],
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["title", "isbn"], name="catalog_boo_title_ec71cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["-created_at"], name="catalog_boo_created_6fa685_idx"
            ),
        ),
    ]
