# Generated by Django 5.2.7 on 2025-12-30 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("due_reminder", "Due Date Reminder"),
                            ("overdue_notice", "Overdue Notice"),
                            ("reservation_ready", "Reservation Ready"),
                            ("reservation_expired", "Reservation Expired"),
                            ("account_summary", "Account Summary"),
                            ("welcome", "Welcome Message"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Django template syntax supported", max_length=200
                    ),
                ),
                (
                    "message_template",
                    models.TextField(help_text="Django template syntax supported"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "days_before_due",
                    models.PositiveIntegerField(
                        blank=True, help_text="For due reminders", null=True
                    ),
                ),
                (
                    "days_overdue",
                    models.PositiveIntegerField(
                        blank=True, help_text="For overdue notices", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["notification_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("due_reminder", "Due Date Reminder"),
                            ("overdue_notice", "Overdue Notice"),
                            ("reservation_ready", "Reservation Ready"),
                            ("reservation_expired", "Reservation Expired"),
                            ("account_summary", "Account Summary"),
                            ("welcome", "Welcome Message"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("both", "Email and SMS"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.loan",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="catalog.patron",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patron", "notification_type"],
                        name="catalog_not_patron__e85d0e_idx",
                    ),
                    models.Index(
                        fields=["scheduled_for", "sent_at"],
                        name="catalog_not_schedul_90a7ac_idx",
                    ),
                ],
            },
        ),
    ]
