# Generated by Django 5.2.7 on 2025-12-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_notificationtemplate_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcopy",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/books/"),
        ),
        migrations.AddField(
            model_name="patron",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="qrcodes/patrons/"
            ),
        ),
    ]
