# Generated by Django 5.2.7 on 2025-12-30 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_bookcopy_qr_code_patron_qr_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_books", models.PositiveIntegerField(default=0)),
                ("total_copies", models.PositiveIntegerField(default=0)),
                ("available_copies", models.PositiveIntegerField(default=0)),
                ("total_patrons", models.PositiveIntegerField(default=0)),
                ("active_patrons", models.PositiveIntegerField(default=0)),
                ("total_loans", models.PositiveIntegerField(default=0)),
                ("active_loans", models.PositiveIntegerField(default=0)),
                ("overdue_loans", models.PositiveIntegerField(default=0)),
                ("returned_today", models.PositiveIntegerField(default=0)),
                ("total_reservations", models.PositiveIntegerField(default=0)),
                ("active_reservations", models.PositiveIntegerField(default=0)),
                ("reservations_fulfilled", models.PositiveIntegerField(default=0)),
                (
                    "total_fines",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "paid_fines",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "outstanding_fines",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_searches", models.PositiveIntegerField(default=0)),
                ("unique_search_queries", models.PositiveIntegerField(default=0)),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PopularBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("checkout_count", models.PositiveIntegerField(default=0)),
                ("reservation_count", models.PositiveIntegerField(default=0)),
                ("search_appearance_count", models.PositiveIntegerField(default=0)),
                (
                    "popularity_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "trending_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "ordering": ["-popularity_score"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("search", "Search Query"),
                            ("view_book", "Book Detail View"),
                            ("checkout", "Book Checkout"),
                            ("checkin", "Book Check-in"),
                            ("reservation", "Reservation Created"),
                            ("login", "User Login"),
                            ("register", "User Registration"),
                            ("page_view", "Page View"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "data",
                    models.JSONField(default=dict, help_text="Additional event data"),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="catalog.book",
                    ),
                ),
                (
                    "book_copy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="catalog.bookcopy",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="catalog.patron",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="catalog_ana_event_t_b9480b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="catalog_ana_user_id_55a66f_idx",
                    ),
                    models.Index(
                        fields=["book", "event_type"],
                        name="catalog_ana_book_id_d58b50_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                (
                    "filters_used",
                    models.JSONField(default=dict, help_text="Applied filters"),
                ),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("clicked_results", models.PositiveIntegerField(default=0)),
                (
                    "search_duration",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["query", "timestamp"],
                        name="catalog_sea_query_5ed94d_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="catalog_sea_user_id_d7391b_idx",
                    ),
                ],
            },
        ),
    ]
