# Generated by Django 5.2.7 on 2026-01-01 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("due_reminder", "Due Date Reminder"),
                            ("overdue_notice", "Overdue Notice"),
                            ("reservation_ready", "Reservation Ready"),
                            ("reservation_expired", "Reservation Expired"),
                            ("account_summary", "Account Summary"),
                            ("welcome", "Welcome Message"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Django template syntax supported", max_length=200
                    ),
                ),
                (
                    "message_template",
                    models.TextField(help_text="Django template syntax supported"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "days_before_due",
                    models.PositiveIntegerField(
                        blank=True, help_text="For due reminders", null=True
                    ),
                ),
                (
                    "days_overdue",
                    models.PositiveIntegerField(
                        blank=True, help_text="For overdue notices", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["notification_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_books", models.PositiveIntegerField(default=0)),
                ("total_copies", models.PositiveIntegerField(default=0)),
                ("available_copies", models.PositiveIntegerField(default=0)),
                ("total_patrons", models.PositiveIntegerField(default=0)),
                ("active_patrons", models.PositiveIntegerField(default=0)),
                ("total_loans", models.PositiveIntegerField(default=0)),
                ("active_loans", models.PositiveIntegerField(default=0)),
                ("overdue_loans", models.PositiveIntegerField(default=0)),
                ("returned_today", models.PositiveIntegerField(default=0)),
                ("total_reservations", models.PositiveIntegerField(default=0)),
                ("active_reservations", models.PositiveIntegerField(default=0)),
                ("reservations_fulfilled", models.PositiveIntegerField(default=0)),
                (
                    "total_fines",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "paid_fines",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "outstanding_fines",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_searches", models.PositiveIntegerField(default=0)),
                ("unique_search_queries", models.PositiveIntegerField(default=0)),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=50)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("active_phone_number", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Visitor",
                "verbose_name_plural": "Visitors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "unique_together": {("first_name", "last_name")},
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=500, unique=True)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                (
                    "isbn13",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("edition", models.CharField(blank=True, max_length=100)),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(default="English", max_length=50)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="books/covers/"),
                ),
                (
                    "sample_pages",
                    models.FileField(blank=True, null=True, upload_to="books/samples/"),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="catalog.author"),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="books", to="catalog.genre"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("copy_number", models.CharField(max_length=50, unique=True)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qrcodes/books/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("checked_out", "Checked Out"),
                            ("reserved", "Reserved"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                            ("processing", "Processing"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_reference_only", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "ordering": ["copy_number"],
            },
        ),
        migrations.CreateModel(
            name="Patron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("faculty", "Faculty/Staff"),
                            ("public", "Public Member"),
                            ("special", "Special Access"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "membership_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qrcodes/patrons/"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("emergency_contact", models.CharField(blank=True, max_length=200)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("membership_expiry", models.DateField(blank=True, null=True)),
                ("max_books", models.PositiveIntegerField(default=5)),
                ("max_loan_days", models.PositiveIntegerField(default=14)),
                ("can_reserve", models.BooleanField(default=True)),
                (
                    "fines_owed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_date", models.DateTimeField()),
                ("returned_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                            ("lost", "Lost"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "fine_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fine_paid", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "book_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="catalog.bookcopy",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "returned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returned_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="catalog.patron",
                    ),
                ),
            ],
            options={
                "ordering": ["-loan_date"],
            },
        ),
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fine_type",
                    models.CharField(
                        choices=[
                            ("overdue", "Overdue Book"),
                            ("lost", "Lost Book"),
                            ("damaged", "Damaged Book"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "date_assessed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_paid", models.DateTimeField(blank=True, null=True)),
                ("paid", models.BooleanField(default=False)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fines",
                        to="catalog.loan",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fines",
                        to="catalog.patron",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_assessed"],
            },
        ),
        migrations.CreateModel(
            name="PopularBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("checkout_count", models.PositiveIntegerField(default=0)),
                ("reservation_count", models.PositiveIntegerField(default=0)),
                ("search_appearance_count", models.PositiveIntegerField(default=0)),
                (
                    "popularity_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "trending_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "ordering": ["-popularity_score"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ready", "Ready for Pickup"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("fulfilled", "Fulfilled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_sms", models.BooleanField(default=False)),
                ("ready_date", models.DateTimeField(blank=True, null=True)),
                ("pickup_deadline", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="catalog.book",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="catalog.patron",
                    ),
                ),
            ],
            options={
                "ordering": ["-reservation_date"],
            },
        ),
        migrations.CreateModel(
            name="ELibrarySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_time", models.DateTimeField(auto_now_add=True)),
                (
                    "items_brought_in",
                    models.TextField(
                        help_text="List of items brought into the e-library"
                    ),
                ),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "items_taken_out",
                    models.TextField(
                        blank=True,
                        help_text="List of items taken out when leaving",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_out_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elibrary_sessions",
                        to="catalog.visitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-Library Session",
                "verbose_name_plural": "E-Library Sessions",
                "ordering": ["-entry_time"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("search", "Search Query"),
                            ("view_book", "Book Detail View"),
                            ("checkout", "Book Checkout"),
                            ("checkin", "Book Check-in"),
                            ("reservation", "Reservation Created"),
                            ("login", "User Login"),
                            ("register", "User Registration"),
                            ("page_view", "Page View"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "data",
                    models.JSONField(default=dict, help_text="Additional event data"),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="catalog.book",
                    ),
                ),
                (
                    "book_copy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="catalog.bookcopy",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="catalog.patron",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="catalog_ana_event_t_b9480b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="catalog_ana_user_id_55a66f_idx",
                    ),
                    models.Index(
                        fields=["book", "event_type"],
                        name="catalog_ana_book_id_d58b50_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("due_reminder", "Due Date Reminder"),
                            ("overdue_notice", "Overdue Notice"),
                            ("reservation_ready", "Reservation Ready"),
                            ("reservation_expired", "Reservation Expired"),
                            ("account_summary", "Account Summary"),
                            ("welcome", "Welcome Message"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("both", "Email and SMS"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.loan",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="catalog.patron",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patron", "notification_type"],
                        name="catalog_not_patron__e85d0e_idx",
                    ),
                    models.Index(
                        fields=["scheduled_for", "sent_at"],
                        name="catalog_not_schedul_90a7ac_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                (
                    "filters_used",
                    models.JSONField(default=dict, help_text="Applied filters"),
                ),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("clicked_results", models.PositiveIntegerField(default=0)),
                (
                    "search_duration",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["query", "timestamp"],
                        name="catalog_sea_query_5ed94d_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="catalog_sea_user_id_d7391b_idx",
                    ),
                ],
            },
        ),
    ]
